server:
  port: 8189
  servlet:
    context-path: /api/v1
spring:
  flyway:
    enabled: true
    create-schemas: true
  application:
    name: hw-spring
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: admin
    url: jdbc:h2:mem:db
  jooq:
    sql-dialect: PosgreSQLDialect

